"""Tests comparing pyCausalArima results against R CausalArima package.

These tests use deterministic data pre-generated by the R package to ensure
reproducible comparison. The data files are stored in the comparison/ directory.
"""

import numpy as np
import pandas as pd
import pytest
from pathlib import Path

from pycausalarima import CausalArima


# Path to comparison data files
COMPARISON_DIR = Path(__file__).parent.parent / "comparison"


@pytest.fixture
def r_comparison_data():
    """Load the deterministic test data generated by R."""
    input_path = COMPARISON_DIR / "input_data.csv"
    if not input_path.exists():
        pytest.skip("R comparison data not found. Run comparison/r_analysis.R first.")

    input_data = pd.read_csv(input_path)
    input_data["date"] = pd.to_datetime(input_data["date"])

    return {
        "y": input_data["y"].values,
        "x1": input_data["x1"].values,
        "dates": pd.DatetimeIndex(input_data["date"]),
        "intervention_date": pd.Timestamp("2014-03-16"),
    }


@pytest.fixture
def r_results_norm():
    """Load R normal inference results."""
    results_path = COMPARISON_DIR / "r_results_norm.csv"
    if not results_path.exists():
        pytest.skip("R results not found. Run comparison/r_analysis.R first.")

    return pd.read_csv(results_path)


@pytest.fixture
def r_final_results():
    """Load R final summary results."""
    results_path = COMPARISON_DIR / "r_final_results.csv"
    if not results_path.exists():
        pytest.skip("R final results not found. Run comparison/r_analysis.R first.")

    df = pd.read_csv(results_path)
    return dict(zip(df["metric"], df["value"]))


class TestRComparisonDeterministic:
    """Tests comparing Python results against R using deterministic data."""

    def test_point_effect_matches_r(self, r_comparison_data, r_final_results):
        """Test that final point effect matches R output."""
        ca = CausalArima(
            y=r_comparison_data["y"],
            dates=r_comparison_data["dates"],
            intervention_date=r_comparison_data["intervention_date"],
            xreg=r_comparison_data["x1"],
        )
        result = ca.fit()

        # Point effect should match within 1% relative tolerance
        np.testing.assert_allclose(
            result.norm.tau[-1],
            r_final_results["point_effect"],
            rtol=0.01,
            err_msg="Point effect differs from R by more than 1%",
        )

    def test_point_effect_sd_matches_r(self, r_comparison_data, r_final_results):
        """Test that point effect standard deviation matches R output."""
        ca = CausalArima(
            y=r_comparison_data["y"],
            dates=r_comparison_data["dates"],
            intervention_date=r_comparison_data["intervention_date"],
            xreg=r_comparison_data["x1"],
        )
        result = ca.fit()

        # SD should match within 2% relative tolerance
        np.testing.assert_allclose(
            result.norm.sd_tau[-1],
            r_final_results["point_effect_sd"],
            rtol=0.02,
            err_msg="Point effect SD differs from R by more than 2%",
        )

    def test_cumulative_effect_matches_r(self, r_comparison_data, r_final_results):
        """Test that cumulative effect matches R output."""
        ca = CausalArima(
            y=r_comparison_data["y"],
            dates=r_comparison_data["dates"],
            intervention_date=r_comparison_data["intervention_date"],
            xreg=r_comparison_data["x1"],
        )
        result = ca.fit()

        # Cumulative effect should match within 1% relative tolerance
        np.testing.assert_allclose(
            result.norm.cumulative[-1],
            r_final_results["cumulative_effect"],
            rtol=0.01,
            err_msg="Cumulative effect differs from R by more than 1%",
        )

    def test_cumulative_effect_sd_matches_r(self, r_comparison_data, r_final_results):
        """Test that cumulative effect SD matches R output."""
        ca = CausalArima(
            y=r_comparison_data["y"],
            dates=r_comparison_data["dates"],
            intervention_date=r_comparison_data["intervention_date"],
            xreg=r_comparison_data["x1"],
        )
        result = ca.fit()

        # This was the critical metric - should now match within 2%
        np.testing.assert_allclose(
            result.norm.sd_cumulative[-1],
            r_final_results["cumulative_effect_sd"],
            rtol=0.02,
            err_msg="Cumulative effect SD differs from R by more than 2%",
        )

    def test_temporal_average_matches_r(self, r_comparison_data, r_final_results):
        """Test that temporal average effect matches R output."""
        ca = CausalArima(
            y=r_comparison_data["y"],
            dates=r_comparison_data["dates"],
            intervention_date=r_comparison_data["intervention_date"],
            xreg=r_comparison_data["x1"],
        )
        result = ca.fit()

        np.testing.assert_allclose(
            result.norm.average[-1],
            r_final_results["temporal_average"],
            rtol=0.01,
            err_msg="Temporal average differs from R by more than 1%",
        )

    def test_temporal_average_sd_matches_r(self, r_comparison_data, r_final_results):
        """Test that temporal average SD matches R output."""
        ca = CausalArima(
            y=r_comparison_data["y"],
            dates=r_comparison_data["dates"],
            intervention_date=r_comparison_data["intervention_date"],
            xreg=r_comparison_data["x1"],
        )
        result = ca.fit()

        np.testing.assert_allclose(
            result.norm.sd_average[-1],
            r_final_results["temporal_average_sd"],
            rtol=0.02,
            err_msg="Temporal average SD differs from R by more than 2%",
        )


class TestRComparisonTimeSeries:
    """Tests comparing full time series results against R."""

    def test_point_effect_correlation(self, r_comparison_data, r_results_norm):
        """Test that point effect time series correlates highly with R."""
        ca = CausalArima(
            y=r_comparison_data["y"],
            dates=r_comparison_data["dates"],
            intervention_date=r_comparison_data["intervention_date"],
            xreg=r_comparison_data["x1"],
        )
        result = ca.fit()

        correlation = np.corrcoef(result.norm.tau, r_results_norm["tau"].values)[0, 1]

        assert correlation > 0.999, f"Point effect correlation ({correlation}) is below 0.999"

    def test_cumulative_effect_correlation(self, r_comparison_data, r_results_norm):
        """Test that cumulative effect time series correlates highly with R."""
        ca = CausalArima(
            y=r_comparison_data["y"],
            dates=r_comparison_data["dates"],
            intervention_date=r_comparison_data["intervention_date"],
            xreg=r_comparison_data["x1"],
        )
        result = ca.fit()

        correlation = np.corrcoef(
            result.norm.cumulative, r_results_norm["cumulative"].values
        )[0, 1]

        assert correlation > 0.9999, f"Cumulative effect correlation ({correlation}) is below 0.9999"

    def test_mean_absolute_difference_tau(self, r_comparison_data, r_results_norm):
        """Test that mean absolute difference in tau is small."""
        ca = CausalArima(
            y=r_comparison_data["y"],
            dates=r_comparison_data["dates"],
            intervention_date=r_comparison_data["intervention_date"],
            xreg=r_comparison_data["x1"],
        )
        result = ca.fit()

        mad = np.mean(np.abs(result.norm.tau - r_results_norm["tau"].values))

        # Mean absolute difference should be less than 0.1
        assert mad < 0.1, f"Mean absolute difference in tau ({mad}) is too large"
