#!/usr/bin/env python3
"""Python script to run CausalArima and compare with R results."""

import numpy as np
import pandas as pd
from pycausalarima import CausalArima

def main():
    print("=" * 60)
    print("Python CausalArima Analysis")
    print("=" * 60)

    # Load data generated by R
    print("\nLoading data from R...")
    input_data = pd.read_csv("comparison/input_data.csv")
    input_data["date"] = pd.to_datetime(input_data["date"])

    y = input_data["y"].values
    x1 = input_data["x1"].values
    dates = pd.DatetimeIndex(input_data["date"])
    intervention_date = pd.Timestamp("2014-03-16")

    print(f"Data loaded: {len(y)} observations")
    print(f"Intervention date: {intervention_date.date()}")

    # Fit the model
    print("\nFitting CausalArima model...")
    ca = CausalArima(
        y=y,
        dates=dates,
        intervention_date=intervention_date,
        xreg=x1,
        n_boot=1000,
    )
    result = ca.fit()

    # Save Python results
    post_dates = dates[dates >= intervention_date]

    # Normal inference results
    results_norm = pd.DataFrame({
        "date": post_dates,
        "tau": result.norm.tau,
        "sd_tau": result.norm.sd_tau,
        "pvalue_tau_left": result.norm.pvalue_tau_left,
        "pvalue_tau_bidirectional": result.norm.pvalue_tau_bidirectional,
        "pvalue_tau_right": result.norm.pvalue_tau_right,
        "cumulative": result.norm.cumulative,
        "sd_cumulative": result.norm.sd_cumulative,
        "pvalue_sum_left": result.norm.pvalue_sum_left,
        "pvalue_sum_bidirectional": result.norm.pvalue_sum_bidirectional,
        "pvalue_sum_right": result.norm.pvalue_sum_right,
        "average": result.norm.average,
        "sd_average": result.norm.sd_average,
        "pvalue_avg_left": result.norm.pvalue_avg_left,
        "pvalue_avg_bidirectional": result.norm.pvalue_avg_bidirectional,
        "pvalue_avg_right": result.norm.pvalue_avg_right,
    })
    results_norm.to_csv("comparison/python_results_norm.csv", index=False)
    print("Normal inference results saved to comparison/python_results_norm.csv")

    # Save final results
    final_results = pd.DataFrame({
        "metric": [
            "point_effect", "point_effect_sd",
            "cumulative_effect", "cumulative_effect_sd",
            "temporal_average", "temporal_average_sd"
        ],
        "value": [
            result.norm.tau[-1],
            result.norm.sd_tau[-1],
            result.norm.cumulative[-1],
            result.norm.sd_cumulative[-1],
            result.norm.average[-1],
            result.norm.sd_average[-1],
        ]
    })
    final_results.to_csv("comparison/python_final_results.csv", index=False)

    print("\n=== Python CausalArima Summary ===")
    print(ca.summary())

    print("\n=== Final Effect Estimates (Python) ===")
    print(f"Point effect: {result.norm.tau[-1]:.3f}")
    print(f"Cumulative effect: {result.norm.cumulative[-1]:.3f}")
    print(f"Temporal average: {result.norm.average[-1]:.3f}")

    # Compare with R results
    print("\n" + "=" * 60)
    print("COMPARISON: R vs Python")
    print("=" * 60)

    try:
        r_final = pd.read_csv("comparison/r_final_results.csv")
        r_results = dict(zip(r_final["metric"], r_final["value"]))

        py_results = {
            "point_effect": result.norm.tau[-1],
            "point_effect_sd": result.norm.sd_tau[-1],
            "cumulative_effect": result.norm.cumulative[-1],
            "cumulative_effect_sd": result.norm.sd_cumulative[-1],
            "temporal_average": result.norm.average[-1],
            "temporal_average_sd": result.norm.sd_average[-1],
        }

        print(f"\n{'Metric':<25} {'R':>12} {'Python':>12} {'Diff':>12} {'Status':>10}")
        print("-" * 75)

        all_close = True
        for metric in py_results:
            r_val = r_results.get(metric, np.nan)
            py_val = py_results[metric]
            diff = abs(r_val - py_val)

            # Use relative tolerance for larger values, absolute for small
            if abs(r_val) > 1:
                is_close = diff / abs(r_val) < 0.05  # 5% relative tolerance
            else:
                is_close = diff < 0.1  # Absolute tolerance for small values

            status = "✓ PASS" if is_close else "✗ FAIL"
            if not is_close:
                all_close = False

            print(f"{metric:<25} {r_val:>12.4f} {py_val:>12.4f} {diff:>12.4f} {status:>10}")

        print("-" * 75)
        if all_close:
            print("Overall: ✓ All metrics within tolerance!")
        else:
            print("Overall: ✗ Some metrics differ significantly")

        # Detailed comparison of time series
        print("\n=== Detailed Time Series Comparison ===")
        r_norm = pd.read_csv("comparison/r_results_norm.csv")

        # Compare point effects over time
        tau_corr = np.corrcoef(r_norm["tau"].values, result.norm.tau)[0, 1]
        cum_corr = np.corrcoef(r_norm["cumulative"].values, result.norm.cumulative)[0, 1]

        print(f"Point effect correlation: {tau_corr:.6f}")
        print(f"Cumulative effect correlation: {cum_corr:.6f}")

        # Mean absolute differences
        tau_mad = np.mean(np.abs(r_norm["tau"].values - result.norm.tau))
        cum_mad = np.mean(np.abs(r_norm["cumulative"].values - result.norm.cumulative))

        print(f"Point effect mean absolute diff: {tau_mad:.4f}")
        print(f"Cumulative effect mean absolute diff: {cum_mad:.4f}")

    except FileNotFoundError:
        print("R results not found. Run r_analysis.R first.")


if __name__ == "__main__":
    main()
